const lessons = [
['AA01','From Chatbots to Agents','Distinguish conversational output from a system that can take actions.',
'A chatbot primarily produces responses. An agentic system can select steps and invoke tools toward a goal, which creates additional responsibility for permissions, state and recovery. Describe what actions are possible and who authorizes them. Keep the model proposal separate from the component that validates and executes an action.',
'A scheduling chatbot suggests a time; an agent with calendar access can create an event. The second system needs participant checks, explicit permission and duplicate prevention before writing.',
'Compare a scheduling chatbot with a scheduling agent using inputs, actions, permissions and failure consequences.',
'Giving a chatbot tools makes every action it proposes authorized.'],
['AA02','Agent Goals & Task Planning','Define a bounded goal with stop conditions and verifiable steps.',
'An agent goal should specify the desired outcome, constraints and conditions for stopping or escalating. Plans break the goal into actions whose results can be checked. Limit time, tool calls and external effects so a failed plan cannot continue indefinitely. Revise a plan using observed results rather than assuming every previous step succeeded.',
'A campus event assistant may find three venue options but cannot book one. It stops after producing verified options or after its search budget is exhausted, then asks an authorized organizer to decide.',
'Write a bounded venue-search plan with acceptance criteria, a tool budget and two escalation conditions.',
'An agent should keep trying indefinitely until it reaches its goal.'],
['AA03','Tools & Function Calling','Validate a proposed tool call before executing it.',
'Tool calling represents an action request using a defined name and arguments. The application must validate argument types, permissions and business rules before execution. Treat tool results as fallible input and avoid exposing unnecessary data to the model. An allowlist limits the available actions; it does not replace per-record authorization.',
'A proposed update_task call names another learner task. Although the arguments match the schema, the server rejects it because the caller does not own that record. Syntax validation and authorization answer different questions.',
'Specify a task-update tool and trace valid, malformed and cross-user requests through its validation boundary.',
'A schema-valid tool call is automatically safe to execute.'],
['AA04','Memory, Context & State','Separate durable workflow state from conversational context.',
'Conversation context is information presented to a model; durable state records what the system has actually done. Store authoritative status changes in the application database with ownership and audit information. Treat remembered statements as claims unless they correspond to verified records. Define retention and deletion rules for stored context.',
'An assistant says a reminder was sent, but the delivery record is still pending. The workflow reports pending and retries according to policy instead of marking it delivered based on the message.',
'Design state fields for a reminder workflow and explain how a reload reconstructs the next action from durable records.',
'A statement in conversation is an authoritative record of an action.'],
['AA05','APIs for Agents','Handle API requests with scoped credentials and explicit failure behavior.',
'An API exposes a contract for requests and responses. An agent integration should validate inputs, protect credentials and interpret status codes before using the response. Timeouts leave some outcomes uncertain, so check idempotency and remote state before repeating a mutation. Limit accessible endpoints and data to the authorized task.',
'A task-creation request times out after reaching the server. Retry with the same idempotency key or query the prior request result; a blind new request could create two tasks.',
'Write request/response examples for a fictional task API, including validation failure, unauthorized access and an ambiguous timeout.',
'A timeout proves the remote action never happened.'],
['AA06','Workflow Automation','Model dependencies, retries and human work as explicit workflow states.',
'A workflow records the order and conditions under which work proceeds. Make transitions explicit, persist the current state and decide which steps can be retried safely. Keep domain completion authoritative: a workflow should reflect an approved result, not manufacture one. Human decisions remain pending until the authorized person acts.',
'A submission workflow waits for a reviewer decision. Advancing the queue item alone cannot approve the submission; the review record must show the required decision and evidence.',
'Draw a submission-review workflow with waiting, approved, revision-needed and cancelled paths, naming the authority for each transition.',
'Moving a workflow card to done proves the underlying domain work is complete.'],
['AA07','Human Approval & Guardrails','Place approval before consequential side effects and recheck its scope.',
'Approval is permission for a specific proposed action under stated conditions. Show the reviewer the relevant inputs and consequences, record their decision and verify that the proposal has not changed before execution. If it changes materially, request fresh approval. Enforce these rules in the action service, not solely in the interface.',
'An organizer approves a message for 20 recipients. If the agent changes the recipient list to 200, the old approval is insufficient. Bind approval to the reviewed proposal and require another decision.',
'Design an approval record for event-message publication and test changed content, changed recipients and expired approval.',
'One approval authorizes any later variation of the proposed action.'],
['AA08','Agent Reliability & Observability','Use event records to diagnose failures and bound retries.',
'Record step identifiers, attempts, outcomes and safe error details so a run can be reconstructed. Do not log secrets or unnecessary personal data. Use bounded retries for recoverable failures and escalate repeated or permanent failures. Monitor actual outcomes, including duplicate prevention and recovery, rather than counting model responses as completed work.',
'A tool returns a validation error three times with unchanged input. Retrying again will not repair the input. Stop, record the failing field and request correction rather than consuming more attempts.',
'Create an event trace for a failed agent run and identify the root cause, safe log fields and appropriate recovery step.',
'Every failure is best handled by retrying the same request.'],
['AA09','Multi-Step Agent Systems','Coordinate dependent steps without sharing excessive authority.',
'Multiple agent steps can divide research, drafting and validation, but each needs a clear input/output contract and minimal permissions. Validate handoffs and retain a single authoritative record of completed actions. Independent review requires different evidence or checks, not merely another agent agreeing with the first. Bound cycles and make human escalation possible.',
'A research step supplies source-linked claims to a drafting step. A validator checks those claims against the sources before publication. If a source is missing, the flow returns for research instead of accepting agreement among agents.',
'Specify a three-step research, drafting and validation system with handoff schemas, permissions and a maximum revision count.',
'Several agents agreeing is equivalent to independent evidence.'],
['AA10','Build an Agent Workflow','Demonstrate a guarded tool-using workflow with replayable evidence.',
'An agent project should expose its goal, tools, permissions, state model and verification rules. Demonstrate normal operation and failure recovery with synthetic or authorized inputs. Record tool proposals separately from accepted actions and show that invalid or unauthorized requests cannot create side effects. Document how to stop the system and inspect a failed run.',
'A notice assistant retrieves approved notices, drafts a summary and waits for publication approval. An injected instruction is ignored, a timeout does not duplicate publication and rejection returns the draft for correction.',
'Deliver a guarded notice workflow, tool contracts, state diagram, normal and negative traces, and an operator recovery guide.',
'A successful happy-path run is sufficient certification for an agent.'],
['SE01','How Software Works','Trace input through computation, storage and visible output.',
'Software executes instructions over data. A user interface collects input, application logic interprets it and storage may preserve the result. Distinguish code, runtime state and persisted data when diagnosing behavior. A screen update does not prove a database write succeeded; verify the result at the boundary responsible for it.',
'A task appears immediately in a list, but the server rejects its save. The UI should show the failure and avoid presenting the task as durably stored. Reloading reveals whether persistence occurred.',
'Diagram a task-creation flow and identify where input validation, authorization, persistence and user feedback belong.',
'If an item is visible on screen, it must already be stored.'],
['SE02','Programming Fundamentals','Express a small problem as deterministic steps and test cases.',
'Programming translates a problem into operations with defined inputs and outputs. Start with a small example, write the expected result and then express the steps needed to obtain it. Separate the algorithm from a particular language syntax. Test an ordinary case, an empty input and an invalid input before expanding the program.',
'To total study minutes, initialize a total, validate each duration and add valid values. Reject a negative duration rather than silently lowering the total. For 20 and 30 minutes, the result is 50.',
'Write pseudocode to total study sessions and show expected outputs for normal, empty and negative-duration inputs.',
'Code is correct once its syntax is accepted.'],
['SE03','Variables, Types & Data','Use types and validation to preserve the meaning of values.',
'Variables name values; types describe which operations and representations are valid. A string containing digits is not automatically a valid numeric measurement. Parse deliberately, validate the allowed range and retain units. Distinguish absent values from meaningful zero values, because treating them as interchangeable can produce misleading results.',
'A form supplies the string 30 for minutes. Convert it to a number and check that it is positive. An empty string is missing input, not evidence of a zero-minute session.',
'Define a study-session record and classify valid and invalid values for title, duration and completion status.',
'Missing data and zero are interchangeable.'],
['SE04','Logic & Control Flow','Trace branches and loops for boundary cases.',
'Conditions choose which instructions run; loops repeat work over a collection or until a condition changes. Make boundaries explicit and ensure loops can terminate. Trace representative values by hand before relying on execution. Pay attention to inclusive versus exclusive comparisons and to what happens when the collection is empty.',
'A reminder is due when its date is today or earlier and it is not completed. Checking only dates before today misses today tasks; ignoring completion sends unnecessary reminders.',
'Write a truth table for the reminder rule and pseudocode that processes zero, one and several tasks.',
'Testing one true branch is enough to verify a conditional rule.'],
['SE05','Functions & Modularity','Define small functions with clear contracts and limited side effects.',
'A function packages behavior behind named inputs and an output. Separate pure calculations from effects such as database writes so each can be checked independently. State preconditions and error behavior, and avoid hidden dependencies on unrelated global state. Modularity helps when boundaries reflect responsibilities rather than arbitrary file size.',
'A completion-rate function accepts completed and total counts and returns no rate when total is zero. A separate function formats the result for display. This keeps the mathematical decision independent from UI wording.',
'Specify and implement or pseudocode a completion-rate function with normal, zero-total and impossible-count tests.',
'A function is reusable even if its required inputs are hidden global variables.'],
['SE06','Data Structures','Choose a collection based on access patterns and uniqueness rules.',
'Lists preserve ordered items, maps associate keys with values and sets represent unique values. Select a structure by the operations the program needs rather than by habit. Define how duplicates and missing keys behave. A structure that is convenient in memory does not itself enforce database consistency or user authorization.',
'Use a list for tasks in display order and a set for completed task IDs when checking membership. If task IDs are duplicated, investigate the source instead of hiding inconsistent records through display logic.',
'Choose structures for ordered tasks, task lookup by ID and unique completed IDs, then trace duplicate and missing-key cases.',
'Using a set in the UI guarantees the database contains no duplicates.'],
['SE07','Web Fundamentals','Explain a browser request and the role of HTML, CSS and JavaScript.',
'A browser requests resources from a server. HTML provides document structure, CSS presentation and JavaScript interactive behavior. URLs identify resources, while HTTP requests and responses carry method, status, headers and optional bodies. Network failures and server errors are normal possibilities, so an interactive page needs visible loading and failure states.',
'A task page loads HTML, then requests task data. If the data request fails, the page should explain the failure rather than display an empty list as if no tasks exist.',
'Draw the requests needed for a task page and define distinct loading, empty, success and error displays.',
'An empty screen always means the server returned no records.'],
['SE08','Frontend Fundamentals','Build a form with accessible controls and honest state feedback.',
'Frontend work connects user actions to application behavior. Use semantic controls with labels, keyboard access and clear validation messages. Track loading and failure explicitly, and prevent accidental duplicate submission without trapping the user. Client validation improves feedback, but the server must still validate and authorize the request.',
'A task form labels the title field, reports a missing title and disables repeated submission while saving. On server rejection it preserves the typed title and explains how to retry.',
'Build or wireframe a task form and test keyboard use, missing input, slow save and rejected save.',
'Client-side form validation makes server validation unnecessary.'],
['SE09','Backend Fundamentals','Enforce business rules at the server boundary.',
'A backend receives untrusted requests, resolves the caller identity and applies authorization and validation before changing state. Use transactions when related writes must succeed together. Return useful errors without exposing secrets. The server cannot rely on a hidden button or a client-supplied owner ID as proof that a mutation is allowed.',
'A learner submits a task update with another learner ID. The server derives the actor from the session and checks record ownership, rejecting the request regardless of the submitted owner field.',
'Specify a task-update handler with validation, ownership checks, transaction boundaries and safe error responses.',
'A client-supplied user ID is trustworthy proof of identity.'],
['SE10','Databases','Model relationships and enforce invariants in persistent storage.',
'A relational database stores records in tables connected by keys. Primary keys identify records; foreign keys preserve relationships; uniqueness and check constraints protect business invariants. Use transactions for related changes and additive migrations to evolve deployed schemas. Keep learner history intact when introducing new fields or versions.',
'An enrollment table references learner and course IDs and has a unique learner/course pair. Two concurrent enrollment requests then cannot create duplicate enrollment records even if both passed an earlier UI check.',
'Design learner, course and enrollment tables with keys, uniqueness rules and an additive optional-field migration.',
'Checking for duplicates in the interface is equivalent to a database constraint.'],
['SE11','APIs & REST','Define a resource API with explicit request, response and error contracts.',
'An API contract states what a caller sends, what the server returns and which failures are possible. Resource-oriented HTTP designs use methods with defined intent, such as reading or creating a resource. Validate payloads, paginate collections and enforce record-level authorization. Do not expose internal errors or assume every response contains the expected shape.',
'POST /tasks accepts a title and returns the created task. A missing title is a validation error; an invalid session is an authentication error. Listing tasks returns only the caller authorized records.',
'Write a task API contract with create/list examples, pagination and validation, authentication and ownership failures.',
'Every non-success response should be treated as an empty successful result.'],
['SE12','Git & Version Control','Use commits and diffs to explain and recover changes.',
'Version control records changes so their purpose and history can be inspected. Review the working diff, stage only related files and write a commit message explaining the behavior changed. Branches isolate work; merging combines histories and may require deliberate conflict resolution. Never commit credentials, and verify the final combined behavior after resolving a conflict.',
'Two branches modify task validation. A conflict is not resolved by blindly accepting one side; compare intended rules, combine them where appropriate and run validation tests on the result.',
'Create a small repository exercise with two related edits, inspect the diff and write focused commit and conflict-resolution notes.',
'A clean merge proves the combined program behaves correctly.'],
['SE13','Testing, Debugging & Deployment','Use a failing behavior to guide a fix and a release decision.',
'A useful test checks observable behavior and fails when that behavior is wrong. Reproduce a defect, narrow its cause and make the smallest justified correction. Run relevant regression tests before building and deploying. Keep environment configuration separate from code, protect secrets and define rollback and health checks before changing a running service.',
'A date-boundary bug omits tasks due today. Add a failing today-case test, correct the comparison, rerun prior cases and verify the deployed task list with a safe test record.',
'Document a boundary defect with a reproduction, regression test, root-cause fix and deployment/rollback checklist.',
'Passing local tests guarantees deployment cannot fail.'],
['SE14','Software Engineering Project','Deliver an API-backed application with reproducible verification.',
'A software project joins specification, implementation, data and operations. Define acceptance criteria before building and retain evidence of normal and negative tests. Document setup without embedding secrets, explain access rules and record limitations. A working UI is only part of the result; persistence, authorization and recovery must also be demonstrated.',
'A study-task app lets each learner create and complete their own tasks. Tests cover invalid titles, duplicate requests and cross-user edits. A README explains setup and an observed deployment health check.',
'Deliver a task application with UI, API, database, focused Git history, tests, security checks and a reproducible README.',
'A project is complete when the homepage looks finished.'],
['DA01','Data Literacy','Frame a data question with a population, measure and decision.',
'Data analysis begins with a question, not a chart. Define the population, time period, measurement and decision the analysis should support. Distinguish observations from interpretations and note what the dataset does not contain. A precise question helps avoid calculating a convenient metric that does not address the actual problem.',
'How many students completed a project this term differs from what proportion of enrolled students completed. The second question requires an enrollment denominator and a consistent period.',
'Write three campus data questions and specify their populations, measures, denominators and intended decisions.',
'Any available metric is suitable for the decision being made.'],
['DA02','Data Types & Structures','Choose data representations that preserve categories, units and missingness.',
'Data can represent categories, counts, measurements, dates or text. The representation affects valid comparisons and calculations. Define units and allowed values in a data dictionary, and distinguish an unknown value from zero or an empty category. Consistent structure makes analysis reproducible and reveals incompatible records before aggregation.',
'Study duration recorded as hours in one row and minutes in another cannot be summed safely until units are standardized. Preserve the original values and record the conversion.',
'Create a five-field study dataset dictionary and normalize a small mixed-unit example with a conversion log.',
'Values in the same column necessarily use the same unit.'],
['DA03','Data Collection & Quality','Identify collection bias and measurement problems before analysis.',
'Collection methods determine whose experiences are represented and how reliably they are measured. Check sampling, coverage, definitions and missing responses. More records do not fix a systematically excluded group. Record how data was obtained and what conclusions the collection method can and cannot support.',
'An online-only survey misses students with unreliable internet. Adding more online responses may improve precision within that group while leaving the coverage gap unchanged.',
'Design a campus connectivity survey plan with alternative collection channels, consistent questions and explicit limitations.',
'A large dataset is automatically representative.'],
['DA04','Data Cleaning','Apply documented cleaning rules while preserving original records.',
'Cleaning addresses duplicates, missing values, invalid ranges and inconsistent categories. Define rules before changing data and retain the raw version. Do not silently replace unknown values with zero or remove inconvenient outliers. Keep a change log explaining what changed, why and how the decision could affect analysis.',
'A negative study duration is invalid, while an unusually long duration may be a real outlier. Flag both for review but do not apply the same automatic deletion rule to them.',
'Clean a fictional six-row study table with duplicate, missing, invalid and unusual values; submit raw data, cleaned data and decisions.',
'Every unusual value is an error that should be deleted.'],
['DA05','SQL & Query Thinking','Translate a question into filtering, joining and aggregation steps.',
'A query selects records, relates tables and summarizes values. Identify the grain of each table before joining: one learner may have many submissions, so a join can multiply rows. Decide whether you need counts of rows, distinct learners or another measure. Check the query against a tiny example whose answer you can calculate by hand.',
'Joining learners to submissions yields three rows for a learner with three submissions. Counting rows overstates the number of learners; count distinct learner IDs when that is the question.',
'Write a query or query plan for learners with completed projects and validate it on a three-learner example with multiple submissions.',
'Counting joined rows always counts the original entities.'],
['DA06','Exploratory Analysis','Use summaries and plots to discover patterns without overstating them.',
'Exploration checks distributions, missingness, relationships and unusual observations before formal conclusions. Compare groups using consistent definitions and inspect both central tendency and variation. Treat discovered patterns as questions to investigate, especially when many comparisons were tried. Record analysis choices so others can distinguish exploration from a preplanned test.',
'Average study time rises because one student reports an extreme value. Compare the median and distribution, inspect the record and explain how sensitive the mean is to it.',
'Explore a small fictional study-hours table using counts, missingness, mean, median and a simple distribution plot.',
'A pattern discovered during exploration is already a proven explanation.'],
['DA07','Statistics for Decision Making','Interpret rates and uncertainty without making unsupported causal claims.',
'Statistics summarizes variation and uncertainty, but conclusions depend on sampling and assumptions. Report denominators with rates and avoid treating a small difference as decisive without context. Association alone does not identify causation; alternative explanations may remain. State what additional evidence would change the decision.',
'Six of ten students and sixty of one hundred students both give a 60 percent completion rate, but the smaller group provides less stable evidence about a wider population. Report group sizes with the rates.',
'Compare two fictional cohort rates, identify uncertainty and propose a fairer comparison for evaluating a workshop.',
'Equal percentages from very different sample sizes provide identical evidence.'],
['DA08','Data Visualization','Choose a chart that supports a specific comparison honestly.',
'A chart encodes data using position, length, color or other visual features. Choose an encoding that matches the question and label units, categories and time periods. Avoid misleading scales and inaccessible color-only distinctions. Include uncertainty or missing-data notes when they affect interpretation, and keep the underlying values available.',
'A bar chart starting its axis near the smallest value exaggerates a small completion-rate difference. Use an appropriate baseline and show the rates and cohort sizes explicitly.',
'Redesign a misleading fictional completion chart and explain your choices of scale, labels, color and annotations.',
'A visually dramatic chart necessarily communicates the data more accurately.'],
['DA09','AI-Assisted Analytics','Verify generated analysis against data definitions and independent checks.',
'AI can suggest queries, formulas and narratives, but it may misunderstand the dataset or invent findings. Supply a data dictionary and a bounded question, then inspect the proposed method. Verify calculations on small cases and trace every narrative claim to an actual result. Do not send sensitive records to an unauthorized service.',
'An assistant describes an increase in monthly revenue from a table containing only transaction counts. Reject the revenue claim because the required price data is absent, even if the query runs.',
'Audit a generated analysis of a fictional task dataset, checking field meanings, calculations, unsupported claims and privacy.',
'A successful query makes the generated interpretation trustworthy.'],
['DA10','Data Analytics Project','Produce a reproducible analysis with justified limits and traceable findings.',
'A data project should connect a decision question to collection, cleaning, analysis and communication. Keep source provenance and transformation records, validate key calculations and report limitations. If a real dataset cannot be lawfully obtained, mark a synthetic exercise clearly rather than implying real-world findings. A reviewer needs enough material to reproduce the conclusion.',
'A campus transport analysis reports waiting-time distributions from authorized observations, explains missing periods and avoids claiming all students are represented. The cleaned data and calculation steps accompany the chart.',
'Deliver an analysis brief, authorized dataset or labeled synthetic substitute, data dictionary, cleaning log, reproducible calculations and visualizations.',
'A polished dashboard replaces the need for data provenance and methods.']
];
export default lessons;
