const lessons = [
['CL01','What Is Cloud Computing?','Explain shared infrastructure and the responsibilities retained by an application owner.',
'Cloud computing provides computing resources through a service rather than requiring the application team to own every machine. Service models divide operational responsibilities differently, but the application owner still needs to manage data, access and configuration. Evaluate the required capability, reliability and cost instead of assuming cloud hosting removes operational work.',
'A managed database may handle machine maintenance while the application team still defines who can read student records. A managed service does not decide the correct access policy for the product.',
'Compare self-managed and managed hosting for a campus task app using responsibility, access, recovery and cost categories.',
'Moving an application to the cloud transfers all security responsibility to the provider.'],
['CL02','Compute, Storage & Networking','Match compute, storage and network resources to an application request.',
'Compute executes code, storage persists data and networking connects components. Trace where a request runs and where its data must remain after the process stops. Distinguish temporary local files from durable storage and private connections from public endpoints. Resource choices affect latency, availability, cost and the consequences of a component failure.',
'An uploaded project file saved only on a temporary application filesystem disappears when the instance is replaced. Store it durably and keep an authorized reference in the database.',
'Diagram a task app with file uploads and identify durable storage, compute, network boundaries and one failure per component.',
'A file written by a cloud process is necessarily durable.'],
['CL03','Cloud Databases','Define access, backup and migration requirements for a managed database.',
'A cloud database still needs a sound schema, least-privilege access and tested recovery. Separate application credentials from administrative credentials and protect connection configuration. Apply migrations deliberately and verify that old records remain valid. A backup is useful only if the team can restore the required data within an acceptable time.',
'A team has daily backups but has never restored one. Run a restore exercise in an isolated environment, check record counts and relationships and document recovery time before relying on the backup plan.',
'Write a database operating plan with role permissions, an additive migration check and an isolated restore verification procedure.',
'The existence of a backup proves recovery will work.'],
['CL04','APIs & Cloud Services','Integrate a service through a bounded and observable contract.',
'Cloud services expose APIs with authentication, quotas and failure modes. Keep credentials server-side when they confer privileged access, validate responses and set timeouts. Handle rate limits with bounded retries and avoid repeating non-idempotent actions blindly. Record safe request identifiers so failures can be investigated without logging secrets.',
'An email service rejects a request due to a temporary quota. Queue a bounded retry using the original message identity rather than creating a new message for every attempt.',
'Specify a notification-service adapter with timeout, rate-limit, duplicate and permanent-failure behavior.',
'Retrying with a new request identity is always harmless.'],
['CL05','Serverless & Modern Deployment','Design stateless execution with external durable state.',
'Serverless execution runs code on demand under platform-defined limits. Do not assume one process will retain memory, local files or a long-running connection between requests. Persist durable state outside the invocation, make retries safe and account for time limits. Deployment configuration should describe required environment values without containing their secret contents.',
'A function stores processed submission IDs in memory. A new instance loses that set and processes a retry twice. Move deduplication into a database uniqueness rule or durable idempotency record.',
'Redesign a fictional submission handler for repeated and interrupted invocations, including durable deduplication.',
'In-memory state survives every serverless invocation.'],
['CL06','Identity, Secrets & Configuration','Separate public configuration from credentials and scope access narrowly.',
'Configuration describes how an application connects to its environment. Some values are public identifiers; others grant authority and must remain secret. Store secrets in an approved secret mechanism, restrict access and rotate exposed credentials. Use different identities for development and production where practical, and never treat hiding a value in frontend code as protection.',
'A privileged database key is embedded in a browser bundle. Removing it from the repository alone is insufficient because it may already be exposed; revoke or rotate it and move privileged operations behind authorized server code.',
'Classify a fictional configuration list as public or secret, assign minimum access and write an exposure-response checklist.',
'A secret is safe if its variable name is obscure.'],
['CL07','Reliability, Scaling & Observability','Define health signals and recovery for a service under changing load.',
'Reliability concerns whether users can complete the intended task, not just whether a process is running. Measure errors, latency and critical workflow outcomes with safe logs and correlation identifiers. Scaling adds capacity but may expose shared-state or database bottlenecks. Define alerts, ownership and recovery procedures that correspond to actual user impact.',
'The homepage returns successfully while task writes fail. A process-only health check stays green; an application health check that verifies the write dependency detects the real outage.',
'Define health checks, three service indicators and a response runbook for a task app whose database becomes unavailable.',
'A reachable homepage proves every application workflow is healthy.'],
['CL08','Deploy a Cloud Application','Demonstrate a release with configuration, health and recovery evidence.',
'A deployment project needs a reproducible build, explicit configuration, controlled access and a recovery plan. Verify the running version through a real user journey and inspect operational signals. Record which checks ran and which remain unexecuted. Use a test environment and authorized data before exposing a service to real users.',
'After deploying a task app, create and reload a task, verify cross-user denial and inspect the health signal. If persistence fails, stop release promotion and return to the previous working version.',
'Deploy an authorized test app and submit build, configuration, health, user-journey and rollback evidence; label any unexecuted step.',
'A successful deployment command proves the application works for users.'],
['CS01','Cybersecurity Fundamentals','Relate a threat to an asset, weakness and practical control.',
'Security protects the confidentiality, integrity and availability of systems and data. Identify the asset and the actor or event that could harm it before choosing a control. A vulnerability is a weakness; risk also depends on likelihood and impact. Work only in authorized environments and use fictional data for learning exercises.',
'Student submissions are an asset. An overly broad read policy is a weakness that may expose them to other users. Restricting access and testing denial directly addresses that risk.',
'Create an asset-threat-control table for a fictional learning portal, with three prioritized risks.',
'Security is only about preventing malicious code execution.'],
['CS02','Identity & Authentication','Explain how identity is established and how sessions can fail.',
'Authentication establishes which identity is making a request, using a mechanism such as a credential or an existing session. Protect credentials, validate sessions server-side and handle expiry and revocation. Authentication does not decide which records the person may access. Error handling should avoid exposing unnecessary account information.',
'A user remains on an open page after their session expires. The next save must revalidate the session and ask them to sign in, preserving unsaved work safely rather than trusting the old UI state.',
'Trace sign-in, session expiry and sign-out for a fictional app and define safe behavior for a save after expiry.',
'A page that loaded while signed in can trust the user forever.'],
['CS03','Authorization & Least Privilege','Enforce ownership and role permissions on every protected operation.',
'Authorization determines whether an authenticated actor may perform a specific action on a specific resource. Grant only the permissions needed and deny by default. Enforce the decision at the backend and database boundary where applicable. Test both allowed and denied cases, including users with the same role in different organizations.',
'Two learners can each edit their own tasks. Changing a task ID in a request must not let one edit the other task, even though both are authenticated learners.',
'Write an access matrix and negative tests for learner, reviewer and operator actions across two users and two organizations.',
'Users with the same role may access all records belonging to that role.'],
['CS04','Data Privacy & Protection','Minimize collection and define justified access and retention.',
'Privacy work begins by asking whether a data item is needed at all. State the purpose, who may access it and when it should be deleted or reviewed. Protect data in transit and storage, but recognize that encryption does not justify unnecessary collection. Use applicable institutional policy and qualified guidance for legal requirements.',
'A study planner needs available hours, not a government identity number. Remove the unnecessary field and define a retention period for obsolete schedules rather than keeping every record indefinitely.',
'Review a fictional student form and produce a minimized field list, access policy and retention decision record.',
'Encryption makes every data-collection choice appropriate.'],
['CS05','Web/Application Security','Place validation and access controls at trust boundaries.',
'Web applications receive untrusted input in forms, URLs and API requests. Validate expected values, use safe database query mechanisms and encode output for its context. Apply authorization before returning or changing records. Security tests should use a controlled test application and verify that malformed or unauthorized input is rejected without exposing private data.',
'A task title containing markup should be displayed as text rather than executed as page behavior. A user ID in the URL must still be checked against the session authorization.',
'Review a fictional task form and API for input, output and ownership boundaries; specify safe tests and expected denials.',
'Input validation alone prevents every web application security issue.'],
['CS06','Social Engineering & Human Risk','Verify requests through independent channels before granting access.',
'Social engineering manipulates trust, urgency or authority to obtain information or actions. Pause when a request seeks credentials, unusual payments or bypassed procedures. Verify through a known independent channel rather than the contact supplied in the suspicious message. Report the event and preserve useful evidence without spreading sensitive material.',
'A message claiming to be university IT asks for a password through a new link. Use the known IT portal or contact directory to verify the request, and do not submit the password.',
'Classify three fictional suspicious messages, identify the persuasion cue and write a safe verification and reporting response.',
'An urgent message from a familiar display name is sufficient proof of authority.'],
['CS07','AI Security','Contain untrusted model inputs and outputs within existing access boundaries.',
'AI systems introduce risks such as malicious instructions in retrieved content, excessive tool authority and leakage through prompts or logs. Treat model output as untrusted until validated. Filter authorized context before calling the model and enforce tool permissions outside it. Test conceptual attacks in a controlled fixture without exposing real secrets.',
'A retrieved note tells the assistant to reveal another learner attempts. The context builder never supplies those attempts, and the tool layer rejects the cross-user request even if proposed.',
'Threat-model a lesson tutor using a fictional injected document and specify context, tool and output controls.',
'The model can be trusted to enforce all access rules from a safety prompt.'],
['CS08','Responsible AI & Bias','Evaluate how a system affects groups and supports correction.',
'Bias can arise from collection, labels, objectives and how outputs are used. Examine whether relevant groups are represented and whether errors have unequal consequences. Avoid treating one aggregate metric as a complete fairness assessment. Include affected people in review where appropriate and provide a process to challenge or correct outcomes.',
'A recommendation system performs well overall but repeatedly excludes students with limited connectivity. Inspect group-specific outcomes and the input assumptions instead of relying solely on the overall score.',
'Review a fictional recommendation system for representation, differential errors and a practical correction process.',
'A high overall accuracy score proves a system is fair.'],
['CS09','Threat/Risk Analysis','Prioritize risks using assets, trust boundaries and plausible impact.',
'Threat analysis asks what must be protected, where trust changes and how a failure could occur. Describe a plausible scenario, existing controls and remaining uncertainty. Prioritize by impact and likelihood rather than by how dramatic a threat sounds. Assign owners and define evidence that a mitigation actually works.',
'A public file URL exposes private project evidence. The mitigation is authorized access to the object, not merely removing the link from a page. Test access as another user and anonymously.',
'Produce a threat model for a project-upload service with boundaries, five risks, owners and verification steps.',
'Hiding a private resource link is equivalent to restricting access.'],
['CS10','Security Assessment Project','Deliver a bounded security review with tested mitigations and limitations.',
'A security assessment needs explicit scope and authorization, an asset model and reproducible observations. Use controlled test accounts and avoid destructive or unauthorized actions. Separate confirmed findings from hypotheses, document mitigations and rerun the relevant tests. A report should explain residual risks and what was outside the assessment.',
'Two test learners exercise evidence access. One can read the other private artifact, so the report records the boundary failure, applies an access-policy correction and verifies both allowed and denied reads.',
'Assess an authorized test app or supplied fictional design; submit scope, threat model, findings, mitigation evidence and residual risks.',
'Finding no issue in a limited review proves the whole system is secure.'],
['CP01','Understanding the Modern Technology Workplace','Connect role expectations to observable contributions and evidence.',
'Technology work combines technical execution with communication, judgment and collaboration. Read role descriptions as collections of responsibilities rather than lists of fashionable tools. Distinguish required capabilities from preferences and identify artifacts that could demonstrate each one. Avoid claiming readiness solely from course completion.',
'A junior role asks for API work and teamwork. A small tested API plus a clear review discussion demonstrates more than a list of tools in a profile. State the scope of your own contribution.',
'Compare two entry-level role descriptions and build a responsibility-to-evidence matrix with current gaps.',
'Listing a tool on a CV proves the ability to use it professionally.'],
['CP02','Communication','Write an actionable update that separates facts, uncertainty and requests.',
'Professional communication helps a reader decide or act. Lead with the relevant outcome, provide supporting evidence and state the requested action or next step. Separate observed facts from assumptions and explain uncertainty precisely. Adapt detail to the audience without hiding a material limitation.',
'Instead of saying the feature is done, report that creation and reload tests passed, cross-user testing remains open and a reviewer is needed before release. This gives the team a usable decision point.',
'Write a project update and a blocker request for a fictional delayed feature, including evidence and ownership.',
'A confident status message is more useful than an accurate qualified one.'],
['CP03','Collaboration & Teamwork','Make ownership, handoffs and review expectations explicit.',
'Collaboration needs shared goals and clear boundaries between contributions. Agree on ownership, interface contracts and review expectations before parallel work. Raise conflicts early and resolve them using the project requirements and evidence. Credit others accurately and make handoffs reproducible rather than dependent on private context.',
'One teammate changes an API response while another builds its UI. Agree on a response contract and notify the consumer before changing it; then test the integrated behavior together.',
'Create a two-person delivery plan with owners, a shared interface, review checkpoints and a disagreement-resolution process.',
'Dividing tasks removes the need to coordinate interfaces.'],
['CP04','Critical Thinking & Problem Solving','Distinguish a symptom from a tested explanation of its cause.',
'Problem solving begins by stating the observed behavior and the expected behavior. Generate plausible explanations, identify evidence that would distinguish them and test the smallest useful hypothesis. Avoid changing many variables at once. Record what the evidence supports and revise the explanation when observations contradict it.',
'A dashboard total is wrong. Check source records, query aggregation and display formatting separately instead of changing all three. A duplicated join explains the count and predicts which cases should fail.',
'Investigate a fictional incorrect task count using three hypotheses, discriminating checks and a justified root-cause conclusion.',
'The first plausible explanation is the root cause.'],
['CP05','Building a Technical Portfolio','Present artifacts with contribution, verification and visibility boundaries.',
'A portfolio should let a reader inspect what you did and how it was checked. Include the problem, your contribution, artifacts, test evidence and limitations. Distinguish a personal exercise from deployed work and a claimed skill from independently reviewed evidence. Share only material you are authorized to make visible.',
'A team project entry names the API endpoint you implemented and links its tests, while crediting the UI work to a teammate. Private user data is excluded from screenshots and repository examples.',
'Draft a portfolio entry with contribution, artifact links, verification state and a privacy/permission review.',
'A team project can be presented as entirely your own work.'],
['CP06','CV, LinkedIn & Professional Presence','Describe capabilities without inventing experience or impact.',
'Professional profiles summarize evidence relevant to a role. Use specific contributions and documented outcomes, keeping claims proportionate to what was actually measured. Do not invent employers, credentials, users or performance improvements. Keep public details consistent and link to permitted artifacts that substantiate important claims.',
'Built a tested task API is supportable with code and tests. Increased productivity by 80 percent is not supportable without a defined measurement and evidence. Use the first claim until the second is established.',
'Rewrite three fictional CV bullets using only supplied evidence and draft a profile summary that states current learning goals.',
'Plausible impact numbers are acceptable when they make a CV stronger.'],
['CP07','Interviews & Demonstrating Competence','Explain a concrete contribution and respond honestly to unknowns.',
'An interview answer should connect a problem, your action, the reasoning and the observed result. Use artifacts or examples when possible and distinguish your contribution from the team effort. When you do not know an answer, explain how you would investigate rather than inventing certainty. Practice receiving feedback and improving clarity.',
'Asked about a bug, explain the failing case, the duplicated join you found, the test you added and the corrected result. Do not claim ownership of unrelated parts of the system.',
'Record or write a two-minute project explanation, answer one follow-up about a limitation and revise it using a clarity rubric.',
'Admitting an unknown is always worse than offering a confident guess.'],
['CP08','Career Readiness Project','Assemble an evidence-backed portfolio and a justified next-learning plan.',
'Career readiness is a set of demonstrated capabilities and remaining gaps, not an unsupported employability score. Select a target role, map its requirements to permitted artifacts and identify missing evidence. Produce consistent application materials and a realistic next-learning plan. Keep verification states visible so reviewers can distinguish practice from approved work.',
'A learner has a tested API but no deployment evidence. The portfolio presents the API honestly and the next plan includes a supervised deployment exercise rather than claiming production experience.',
'Submit a role-to-evidence matrix, portfolio entry, CV, interview response and a thirty-day gap-driven learning plan.',
'Completing a career course guarantees employment readiness for every role.'],
['EI01','Problems Worth Solving','Describe an observed user problem before choosing a solution.',
'A product idea should start with a specific person, situation and recurring difficulty. Separate direct observations from assumptions about causes or willingness to pay. Consider the workaround already used and the cost of doing nothing. A problem statement should remain meaningful even if the first proposed technology is removed.',
'Students coordinate study rooms through repeated messages and sometimes arrive to find no space. The problem is unreliable coordination, not the absence of an AI app. Investigate the current process first.',
'Write three campus problem statements with affected users, observed behavior, current workaround and untested assumptions.',
'A novel technology automatically identifies a worthwhile customer problem.'],
['EI02','Customer Discovery','Ask about real behavior without leading participants toward your idea.',
'Discovery interviews seek evidence about existing behavior, constraints and priorities. Ask open questions about recent experiences rather than asking whether someone likes your proposed solution. Obtain appropriate consent, minimize personal data and distinguish quotations from interpretations. A small interview sample provides leads and uncertainty, not proof of a whole market.',
'Would you use my smart booking app invites politeness. Tell me about the last time you tried to find a study room reveals actions, obstacles and alternatives without suggesting the answer.',
'Write a five-question interview guide and analyze three fictional responses, labeling observations and assumptions separately.',
'Positive reactions to a pitch prove demand.'],
['EI03','Evaluating Ideas','Compare ideas using evidence, risk and testability.',
'Evaluate an idea by the importance of the problem, who experiences it, existing alternatives and the hardest assumptions. Separate evidence from confidence and choose a low-cost test of the riskiest claim. Feasibility, desirability and sustainability are different questions. A scoring table helps organize judgment but does not turn guesses into facts.',
'A room-booking idea assumes staff will maintain availability data. Before building a polished app, test whether a small group can keep a shared availability record accurate for a week.',
'Compare two fictional ideas, identify the highest-risk assumption for each and design a discriminating experiment.',
'A high score in an idea matrix proves the business will succeed.'],
['EI04','Value Proposition','State a concrete user benefit relative to an existing alternative.',
'A value proposition connects a specific user problem to a benefit the user can recognize. Explain the alternative currently used and why the proposed change could be better. Avoid vague claims such as smarter or revolutionary. Define a measurable outcome and test whether users value it enough to change behavior.',
'Find an available room without messaging five groups is more concrete than AI-powered campus innovation. Test whether the proposed process actually reduces unsuccessful searches.',
'Write a value proposition for a fictional room-coordination service with target user, alternative, benefit and a measurable test.',
'A list of product features is the same as a user value proposition.'],
['EI05','Business Models','Explain who benefits, who pays and which costs recur.',
'A business model describes how value is delivered and sustained. Identify the user, payer, distribution route and recurring costs, which may be different from initial build costs. Use explicit assumptions and simple calculations before projecting growth. Do not present fictional revenue or demand as measured results.',
'A service earns a fictional 100 units per month but costs 120 units to operate. More users may worsen the loss if costs scale faster than revenue. Separate fixed and per-user costs before extrapolating.',
'Build a fictional unit-economics worksheet with payer, price, fixed costs, variable costs and a sensitivity check.',
'Growing user numbers always improve financial sustainability.'],
['EI06','Building an MVP','Choose the smallest experiment that tests a consequential assumption.',
'A minimum viable product is a bounded way to learn about a value proposition, not a license to ignore safety or quality. Select the assumption to test and include only the capabilities needed for that test. Define a success threshold, protect participant data and state what the prototype cannot do. A manual service may test demand before software is necessary.',
'Before building automated room matching, manually coordinate a small authorized group using a shared schedule. Measure successful bookings and effort to learn whether coordination solves the problem.',
'Specify an MVP experiment with target participants, scope, exclusions, success threshold and safe data handling.',
'An MVP must contain every major feature of the eventual product.'],
['EI07','Testing, Feedback & Iteration','Use observed behavior to decide whether to change, continue or stop.',
'An experiment needs a question, procedure and decision rule. Observe actual behavior and record negative feedback as well as positive reactions. Compare results with the original threshold instead of redefining success afterward. Choose the next change based on the evidence and preserve a record of what was learned.',
'A booking prototype gets compliments but only one of ten participants completes a booking. Investigate the failed steps and value assumption rather than counting compliments as adoption.',
'Analyze fictional MVP results, distinguish behavior from opinion and propose one justified iteration with a new test.',
'Positive feedback is equivalent to demonstrated adoption.'],
['EI08','Startup/MVP Project','Present a traceable chain from problem evidence to an MVP decision.',
'A startup project should show the problem, discovery evidence, risky assumptions, experiment and result. Keep participant information protected and clearly label simulated evidence. Explain what changed after feedback and what remains unknown. The final recommendation may be to stop or change direction; that can be a sound outcome when supported by evidence.',
'Interviews reveal that room availability data is unreliable, and a manual trial shows maintaining it is costly. The team narrows the service to one managed venue instead of claiming campus-wide readiness.',
'Deliver a problem brief, discovery notes, value proposition, MVP, test results, iteration decision and next-step risk register.',
'A project is unsuccessful if evidence suggests abandoning the original idea.']
];
export default lessons;
