const lessons = [
['VC01','What Is Vibe Coding?','Explain the developer responsibility for understanding and verifying AI-generated changes.',
'AI-assisted development uses a coding assistant to propose or implement software changes. The developer remains responsible for requirements, architecture, access boundaries and the observed behavior of the result. Start with a small task, inspect the proposed code and compare it with acceptance criteria. A generated explanation or completion claim is not execution evidence. Preserve a manual path when the assistant is unavailable and disclose assistance honestly.',
'An agent implements a task counter and says tests pass, but provides no run output. Inspect the diff, execute a test with zero and multiple tasks and record the actual result. If the counter includes deleted tasks, reject the completion claim and investigate the query.',
'Review a small generated task-counter proposal. Explain its behavior, identify a boundary case and record an independent verification result.',
'A coding agent completion message is sufficient evidence that the feature works.'],
['VC02','Idea → Build Specification','Convert an idea into bounded requirements, data rules and acceptance criteria.',
'A build specification states the user, desired outcome, inputs, observable behavior and exclusions. Include unhappy paths and data ownership rather than describing only a screen. Separate required behavior from optional polish and identify unresolved decisions before coding. The specification should let a reviewer decide whether a change meets the need without guessing what the author intended.',
'For a study-task organizer, require an owner-scoped task list, nonempty titles and persistence after reload. Exclude shared tasks from the first version. Acceptance includes rejecting another user update and showing a failed-save message without losing input.',
'Write a task-organizer specification with three success criteria, three failure cases, a data model and explicit exclusions.',
'A screenshot or one-sentence idea fully specifies application behavior.'],
['VC03','Prompting Coding Agents','Give a coding agent bounded scope, relevant context and verification obligations.',
'An agent brief should identify the outcome, constraints, repository entry points and tests that demonstrate success. Ask the agent to inspect existing code before choosing changes and to preserve established architecture unless the task requires otherwise. Specify stop conditions for missing information or unsafe effects. Require a diff summary and actual validation results, keeping secrets out of prompts and logs.',
'A request to fix task validation names the current form, server command and database constraint. It asks for the smallest change and tests for empty and whitespace-only titles. It does not authorize replacing authentication or deploying the app.',
'Draft an agent brief for a validation fix with scope, inspection targets, acceptance tests, prohibited secret handling and escalation conditions.',
'Broad permission to improve the codebase is the best default for a small defect.'],
['VC04','Understanding Existing Codebases','Trace a feature through its real code and data paths before modifying it.',
'Read repository instructions, package scripts, recent history and the files reached by the feature. Trace UI events through actions or handlers, services, database operations and tests. Distinguish active runtime code from examples or unused files. Record existing behavior and run relevant checks before editing so pre-existing failures are not confused with regressions.',
'A page calls a server action that invokes a database command. A similarly named client helper is unused. Change the active command path and verify its RLS behavior instead of fixing only the unused helper.',
'Map a task-creation feature from route to persisted record, identify its authorization boundary and list the tests that exercise it.',
'A filename or architecture document proves a feature is wired into production.'],
['VC05','Build Your First AI-Assisted Application','Build a small vertical slice and verify each boundary.',
'A vertical slice connects one useful user action from interface to persistent result. Start with a minimal task and add validation, error feedback and a reproducible check before expanding. Review every generated dependency and code change for necessity. Keep progress in small commits and distinguish a local prototype from a deployed service.',
'Build task creation first: enter a title, validate it, save the record and reload the list. Test an empty title and a failed save. Only after this slice works should filters or visual refinements be added.',
'Implement a single-user local task-creation slice or a supplied sandbox equivalent, with success, invalid-input and persistence checks.',
'Generating all screens first is proof that the underlying application is complete.'],
['VC06','AI-Assisted Frontend Development','Verify accessible UI behavior across loading, empty, error and success states.',
'Use an assistant to propose UI changes within the existing component and style system. Inspect semantics, labels, keyboard operation and responsive behavior as well as appearance. Separate local form state from confirmed server state. Preserve user input after recoverable errors and prevent duplicate submissions while a request is pending without permanently disabling recovery.',
'A task form looks correct but its submit control is a clickable div. Replace it with a semantic button, associate the label with the input and test keyboard submission. On failed save, retain the title and show an actionable error.',
'Improve a task form and capture keyboard, narrow-screen, empty-list, slow-save and failed-save observations.',
'Visual similarity to a mockup is sufficient frontend verification.'],
['VC07','Backend, Database & APIs','Apply generated server and schema changes without weakening ownership or history.',
'Backend changes must validate untrusted input and derive identity from the authenticated session. Use canonical service boundaries and database constraints rather than inventing a parallel write path. Prefer additive migrations, inspect row-level policies and verify cross-user denial. Keep secrets server-side and define request, response and error contracts so the UI can recover correctly.',
'Adding due dates requires a nullable column for existing tasks, input validation for new values and unchanged owner-scoped updates. A generated policy allowing every authenticated user to update all tasks must be rejected.',
'Design and test an additive due-date change with API validation, old-record compatibility and two-user access checks.',
'An authenticated database role should be allowed to update every application record.'],
['VC08','Debugging With AI','Use reproducible evidence to isolate and repair a defect.',
'Give the assistant the expected behavior, actual behavior, minimal reproduction and relevant safe logs. Form hypotheses and inspect the responsible state before editing. Change the smallest causal element and add a regression test that would fail on the original defect. Avoid repeated speculative rewrites, and remove temporary diagnostics that expose unnecessary information.',
'A task count doubles only when a task has two comments. The reproduction suggests a join multiplication problem. Count distinct tasks or change the query structure, then verify zero, one and multiple-comment cases.',
'Investigate a duplicated task-count bug with a minimal dataset, hypothesis log, root-cause fix and regression evidence.',
'Repeatedly asking an agent to try another patch is equivalent to diagnosing the cause.'],
['VC09','Git/GitHub for AI Development','Review generated diffs and preserve an understandable change history.',
'Inspect repository status before work, keep unrelated changes intact and use a focused branch for a bounded task. Read the diff before staging, checking for accidental files, secrets and scope expansion. Commit coherent changes with the problem and validation evidence. A pull request should explain behavior and limitations to someone who did not see the agent conversation.',
'An agent fixes a label but also reformats the entire repository. Retain the necessary label change and avoid bundling unrelated churn. Review the final diff and run the relevant check before creating a focused commit.',
'Prepare a small change with a clean scoped diff, commit message and pull-request description that names actual validation and remaining limits.',
'Every file changed by an agent belongs in the task commit.'],
['VC10','Testing & E2E Verification','Verify the user journey and negative cases against real persisted behavior.',
'Unit tests check focused logic, integration tests check boundaries and browser tests check a user journey. Use assertions that would catch the defect or missing behavior, not just mirror implementation details. Verify persistence after reload and exercise invalid input, interrupted requests and unauthorized access. Never replace production logic with a test-only shortcut to obtain a green result.',
'A browser test creates a task and sees it in memory, but never reloads. Add a reload and verify the saved task through the real backend, then test that a second user cannot edit it. Record skipped tests as unverified.',
'Create a task-journey test plan and executable tests where a test environment exists, covering create, reload, failure recovery and cross-user denial.',
'A passing mocked UI test proves the production persistence path works.'],
['VC11','Security & Responsible Vibe Coding','Review generated changes for secrets, permissions and unsafe trust assumptions.',
'Generated code can introduce excessive privileges, unsafe input handling or accidental secret exposure. Inspect the diff at trust boundaries and test authorization outside the UI. Use only authorized test accounts and synthetic data, avoid posting credentials to an assistant and rotate any credential that was exposed. Human responsibility includes understanding why a mitigation works and reporting residual risk.',
'A generated client component embeds an administrative key to bypass a failed query. Remove the privileged client path, rotate any exposed key and repair the authorized server/database path. Passing the query is not worth removing the access boundary.',
'Perform a security review of a fictional generated task feature with secret, input, output, ownership and dependency checks, then document mitigations and retests.',
'A workaround that makes the feature pass is acceptable even if it bypasses authorization.'],
['VC12','Production Application Capstone','Deliver and explain an AI-assisted application with independently checkable release evidence.',
'The capstone joins requirements, architecture, implementation and operations into one reviewable delivery. Keep agent work bounded and record your own technical decisions. Demonstrate a working UI and backend/data path where applicable, focused Git history, unit/integration/browser tests, security checks and an actual authorized deployment. Include health observations, recovery instructions, a README and reflection on errors caught. Unexecuted checks or an undeployed prototype cannot be described as a production release.',
'A study-task application is deployed to a test environment, tested through creation and reload, and checked with two users for isolation. A release report links the exact commit, test outputs, deployment, README and rollback procedure. An unresolved security failure blocks approval even if the UI works.',
'Submit requirements, architecture decisions, implementation, repository and Git history, working UI, applicable backend/data, tests, security checks, deployment, E2E evidence, README and a reflection distinguishing agent output from your verification.',
'A production-oriented capstone can claim deployment or security verification without executing those checks.']
];
export default lessons;
