// Short labels explain only the public authored material. No protected keys.
export default {
  AF01:{motif:'Choose the right decision method',
    concept:[['Fixed rule','Explicit condition','data'],['Learned model','Patterns from examples','proposal'],['Human judgment','Uncertainty and consequences','review']],
    example:[['Room capacity','Explicit limit → fixed rule','data'],['Maintenance text','Classification → model assistance','proposal'],['Uncertain request','Escalate to a person','review']],
    correction:'Automation may follow fixed rules. Select a method from the task, evidence and cost of error.',
    fields:['Campus task','Input','Rule / model / human','Expected output','Error consequence'],rows:6},
  PC07:{motif:'Filter before building context',
    concept:[['Current task','State and constraints','data'],['Permission filter','Authorized and relevant only','review'],['Context bundle','Minimum necessary material','evidence']],
    example:[['Include','Approved lesson + own attempt','evidence'],['Exclude','Another learner submission','denied'],['Exclude','Protected answer key','denied']],
    correction:'Permission and relevance determine what enters context. More data does not create authority.',
    fields:['Context field','Include / exclude / conditional','Permission basis','Reason','Source reference'],rows:4},
  AA07:{motif:'Approval binds to the proposal',
    concept:[['Proposal','Content + recipients + scope','proposal'],['Human decision','Review exact proposal','review'],['Execution gate','Recheck unchanged scope','verified']],
    example:[['Reviewed message','20 recipients','review'],['Changed proposal','200 recipients','proposal'],['Stop and reapprove','Old approval is insufficient','denied']],
    correction:'A materially changed proposal needs fresh approval before any consequential side effect.',
    fields:['Proposal version','Content change','Recipient change','Approval expiry','Expected gate result'],rows:3},
  SE10:{motif:'Relationships protected by constraints',
    concept:[['Learner','Primary key: learner_id','data'],['Enrollment','Foreign keys + unique pair','data'],['Course','Primary key: course_id','data']],
    example:[['Request A','Same learner + course','proposal'],['Request B','Same learner + course','proposal'],['Database constraint','One unique enrollment pair','verified']],
    correction:'Enforce uniqueness in the database; two requests can both pass an earlier UI check.',
    fields:['Table / field','Primary or foreign key','Constraint','Concurrent test','Additive migration'],rows:3},
  DA08:{motif:'Make the comparison honest',
    concept:[['Question','Name the intended comparison','review'],['Encoding','Scale + units + labels','data'],['Interpretation','Context + uncertainty','evidence']],
    example:[['Truncated baseline','Can exaggerate a small difference','warning'],['Appropriate baseline','Preserves comparison context','review'],['Rates and group sizes','Show alongside the chart','evidence']],
    correction:'Dramatic appearance is not accuracy. Explain the baseline and retain rates, cohort sizes and uncertainty.',
    fields:['Comparison question','Scale and baseline','Units / labels','Non-color cue','Limitations'],rows:3},
  CS03:{motif:'Identity is only the first gate',
    concept:[['Identity','Who is making the request?','data'],['Record permission','Owner + role + organization','review'],['Operation','Allow or deny at the boundary','verified']],
    example:[['Learner A → task A','Own record edit','verified'],['Learner A → task B','Changed ID does not grant access','denied'],['Learner B → task B','Own record edit','verified']],
    correction:'Being authenticated does not authorize access to another learner’s record.',
    fields:['Actor / role','Record owner','Organization','Operation','Expected result','Observed evidence'],rows:4},
  EI06:{motif:'Test the assumption before scaling',
    concept:[['Assumption','What must be true?','proposal'],['Small experiment','Bounded and authorized','review'],['Observed result','Measure before expanding','evidence']],
    example:[['Shared schedule','Manual room coordination','data'],['Authorized group','Try the booking process','review'],['Measure','Successful bookings + effort','evidence']],
    correction:'An MVP tests a consequential assumption; it need not automate the whole product.',
    fields:['Participants','Assumption','Included scope','Excluded scope','Success threshold','Safe data handling'],rows:3},
  VC10:{motif:'Follow the record beyond the screen',
    concept:[['Create','Use the real backend','data'],['Reload','Verify persisted state','evidence'],['Second user','Verify unauthorized edit denial','denied']],
    example:[['Memory-only test','Task appears before reload','proposal'],['Reload + backend','Saved task still exists','evidence'],['Different learner','Cannot edit that task','denied']],
    correction:'A mocked or memory-only pass is not production evidence. Skipped checks remain unverified.',
    fields:['Journey step','Expected state','Actual persisted state','Reload / recovery','Second-user check','Evidence / skipped'],rows:4},
};
