import type {Metadata} from "next";
import {Landmark,ShieldCheck} from "lucide-react";
import {assertCan,governedOrganizationIds} from "@/domain/identity/actor";
import {requireActor} from "@/server/services/actor";
import {createSupabaseServerClient} from "@/lib/supabase/server";
import {getGovernanceWorkspace} from "@/server/services/flywheel-service";
import {createContributionProgramAction,createContributionTaskAction,createFundingProgramAction,reconcileFundingAction,reviewContributionAction} from "@/server/actions/flywheel";
import {Button} from "@/components/ui/button";
import {Card,CardContent,CardDescription,CardHeader,CardTitle} from "@/components/ui/card";
import {Input,Select,Textarea} from "@/components/ui/field";
import {Badge,EmptyState} from "@/components/ui/feedback";
export const metadata:Metadata={title:"Flywheel governance"};
export default async function GovernancePage(){const actor=await requireActor();assertCan(actor,"organization.manage");const organizationIds=governedOrganizationIds(actor);const supabase=await createSupabaseServerClient();const data=await getGovernanceWorkspace(supabase,organizationIds);return <div className="space-y-5"><div><h1 className="text-2xl font-semibold">Flywheel governance</h1><p className="mt-1 text-sm text-ink-muted">Create governed capacity and work, reconcile real transactions and independently review contributions.</p></div>
<div className="grid gap-5 xl:grid-cols-2"><Card><CardHeader><CardTitle>Funding program</CardTitle><CardDescription>Currency uses integer minor units. Eligibility is versioned.</CardDescription></CardHeader><CardContent><form action={createFundingProgramAction} className="space-y-3"><Select name="organizationId" required>{actor.memberships.filter(m=>organizationIds.includes(m.organizationId)).map(m=><option key={m.organizationId} value={m.organizationId}>{m.organizationName}</option>)}</Select><Input name="name" required placeholder="Program name"/><Input name="code" required pattern="[a-z0-9-]+" placeholder="program-code"/><div className="grid grid-cols-2 gap-3"><Select name="kind"><option value="fund_a_seat">Fund a seat</option><option value="cohort">Cohort</option><option value="community">Community</option><option value="program">Program</option></Select><Input name="currency" required minLength={3} maxLength={3} placeholder="USD"/></div><Input name="policyVersion" required placeholder="Policy version"/><Input name="requiredKeys" placeholder="country_code,student_status"/><Button type="submit">Create active program</Button></form></CardContent></Card>
<Card><CardHeader><CardTitle>Contribution program</CardTitle></CardHeader><CardContent><form action={createContributionProgramAction} className="space-y-3"><Select name="organizationId" required>{actor.memberships.filter(m=>organizationIds.includes(m.organizationId)).map(m=><option key={m.organizationId} value={m.organizationId}>{m.organizationName}</option>)}</Select><Input name="name" required placeholder="Program name"/><Select name="kind"><option value="data">Data</option><option value="research">Research</option><option value="digitization">Digitization</option><option value="localization">Localization</option><option value="evaluation">AI evaluation</option><option value="community">Community</option><option value="solution">Solution</option></Select><Input name="license" placeholder="Data/research license"/><Button type="submit">Publish program</Button></form></CardContent></Card></div>
<Card><CardHeader><CardTitle>Create contribution task</CardTitle></CardHeader><CardContent>{data.contributionPrograms.length===0?<EmptyState icon={Landmark} title="Create a contribution program first" description="Tasks always belong to a governed program."/>:<form action={createContributionTaskAction} className="space-y-3"><Select name="programId" required>{data.contributionPrograms.map(p=><option key={String(p.id)} value={String(p.id)}>{String(p.name)}</option>)}</Select><Input name="title" required placeholder="Task title"/><Textarea name="instructions" required minLength={20} placeholder="Complete instructions, expected method and quality requirements"/><Button type="submit">Publish available task</Button></form>}</CardContent></Card>
<Card><CardHeader><CardTitle>Pending funding reconciliation</CardTitle><CardDescription>No transaction is confirmed until its payment reference is recorded.</CardDescription></CardHeader><CardContent className="space-y-3">{data.commitments.length===0?<p className="text-sm text-ink-muted">No pending commitments.</p>:data.commitments.map(c=><form key={String(c.id)} action={reconcileFundingAction} className="flex flex-wrap items-center gap-2 rounded-xl border border-white/8 p-3"><input type="hidden" name="commitmentId" value={String(c.id)}/><span className="mr-auto text-sm">{String(c.currency)} {(Number(c.amount_minor)/100).toFixed(2)}</span><Input name="providerReference" required placeholder="Provider reference" className="max-w-xs"/><Select name="success" className="max-w-32"><option value="true">Confirmed</option><option value="false">Failed</option></Select><Button size="sm">Reconcile</Button></form>)}</CardContent></Card>
<Card><CardHeader><CardTitle className="flex items-center gap-2"><ShieldCheck className="size-4 text-accent"/>Independent contribution review</CardTitle></CardHeader><CardContent className="space-y-3">{data.pending.length===0?<p className="text-sm text-ink-muted">No submissions awaiting review.</p>:data.pending.map(s=><form key={s.id} action={reviewContributionAction} className="space-y-3 rounded-xl border border-white/8 p-4"><input type="hidden" name="submissionId" value={s.id}/><div className="flex justify-between"><span className="text-sm">Submission {s.id.slice(0,8)}</span><Badge tone="warning">Awaiting review</Badge></div><pre className="overflow-auto rounded-lg bg-black/20 p-2 text-xs text-ink-muted">{JSON.stringify(s.provenance,null,2)}</pre><Textarea name="notes" required minLength={5} placeholder="Review rationale"/><div className="flex gap-2"><Button name="decision" value="accepted" size="sm">Accept</Button><Button name="decision" value="revision_required" variant="secondary" size="sm">Request revision</Button><Button name="decision" value="rejected" variant="danger" size="sm">Reject</Button></div></form>)}</CardContent></Card></div>}
