-- Replace only the original reference prompts. Preserve authored content,
-- activity IDs, enrollment, completions, prerequisites and evidence rules.
-- These are reflection checks, not automatically graded assessments.
with content(module_slug, lesson, lab, reflection) as (values
('module-ai-concepts',
 'Objective: distinguish generated text from verified knowledge. A language model generates tokens using patterns learned during training and the context supplied at inference time. Fluent output does not establish that a claim is true. Training is different from retrieval: a retrieved document can provide current evidence, but the generated summary must still be checked against it. For example, a plausible university deadline is unusable until it matches the official notice. Separate the generated claim, its supporting source and your verification decision.',
 'Use a short public university notice. Ask an available AI tool to summarize it, or manually draft a summary if no tool is available. List three claims from the summary beside exact supporting passages. Identify any unsupported claim and rewrite it. Submit the notice source, claim-to-passage comparison and corrected summary. Do not include student personal information.',
 'A model confidently states a deadline but cannot provide a supporting notice. Explain why fluency is insufficient and what source you would consult before acting. This reflection records practice; it does not verify mastery.'),
('module-ai-limitations',
 'Objective: identify unsupported claims and design a verification step. Models can invent citations, repeat biases, omit relevant context and use outdated information. Repeating the same question is not independent verification. Check claims against primary evidence, including the date and scope of that evidence. A citation is useful only after you open it and confirm that it supports the claim. When evidence is unavailable, state uncertainty and defer the decision instead of filling the gap with a guess.',
 'Choose a public factual explanation with three checkable claims. Record each claim, a primary source, its publication date and whether it supports the claim. Correct one unsupported or overstated statement. If every claim is supported, explain a limitation of the available evidence. Submit your verification table and corrected explanation.',
 'Two AI tools repeat the same claim and cite a page that does not contain it. Is this independent confirmation? Explain your next verification step and how you would communicate uncertainty.'),
('module-prompt-design',
 'Objective: specify a task with observable acceptance criteria. A useful prompt states the goal, relevant context, constraints and output format. Supply examples when the desired format is ambiguous. Ask for missing information to be identified instead of invented. For a study plan, specify available hours, topics and a deadline, then check that the proposed hours add up. Improve one instruction at a time so you can connect a change in the output to a change in the prompt. A detailed prompt still requires output verification.',
 'Write a prompt for a five-hour weekly study plan with three named topics. Define acceptance checks for total hours, topic coverage and output format. Run it with an available tool or evaluate a manually drafted response. Revise one instruction after finding a failed check. Submit both prompt versions, the response you evaluated and the check results.',
 'A response follows your requested format but invents available study hours. Which missing constraint would you add, and how would you test that the revised response satisfies it?'),
('module-ai-tool-workflow',
 'Objective: place human checks at the points where an AI error could cause harm. Describe a workflow as inputs, transformation, validation and an authorized action. Keep generation separate from actions such as publishing or sending messages. Use only the minimum data required, remove personal information and keep a record of decisions. If validation fails, return the item for correction; if the tool is unavailable, retain a manual route. Success means an accepted result, not merely a successful API response.',
 'Design a workflow that drafts a campus event announcement from an approved brief. Specify inputs, privacy checks, drafting, fact verification, approval and publication. Add a manual fallback and a rule preventing duplicate publication. Submit the workflow and trace one incorrect-date example through its correction path.',
 'The AI service returns successfully, but the draft changes the event venue. Explain why the workflow must stop before publication and who or what can authorize the corrected version.'),
('module-data-interpretation',
 'Objective: distinguish a supported comparison from a causal claim. A percentage needs a denominator and a time period. A chart can conceal missing groups, inconsistent units or a truncated axis. Correlation does not establish that one variable caused another; selection effects and other variables may explain the pattern. For example, higher scores among workshop attendees do not prove the workshop caused improvement if attendance was voluntary. State what the data shows, what remains unknown and what additional comparison would help.',
 'Compare two fictional cohorts: 18 of 30 students and 24 of 60 students completed a project. Calculate each completion rate and explain why the larger completion count does not imply a higher rate. Write one supported conclusion and one unsupported causal claim. Submit your calculations, conclusions and the extra data needed to investigate causality.',
 'A chart shows more completed projects after an AI workshop. Name two alternative explanations and describe a comparison that would make the causal claim more credible.'),
('module-data-quality',
 'Objective: assess whether data is fit for a decision. Define what each field measures, its unit and how records were collected. Check missing values, duplicates, impossible values and inconsistent categories before analysis. Missing is not the same as zero. Removing records can change which groups are represented, so record each cleaning decision and retain the original data. A large sample can still be biased when its collection method excludes the people the decision affects.',
 'Create a fictional six-row study-hours dataset with one duplicate, one missing value and one impossible negative value. Define validation rules and produce a cleaned copy without silently turning missing values into zero. Submit both versions, a change log and one way your fictional sampling method could bias a conclusion.',
 'A survey was distributed only to students with reliable internet access. Explain why adding more responses from the same channel may not fix its coverage bias and propose another collection route.'),
('module-applied-ai-projects',
 'Objective: turn a problem into a small deliverable with checkable evidence. Define the user, the problem and an observable acceptance criterion before selecting a tool. Separate a prototype from a deployed service. Test normal, invalid-input and dependency-failure cases. Keep source changes in version control, document how to reproduce the result and record limitations. An AI-generated implementation is a proposal: inspect it, test it and review data access before release. Project completion and verified skill are separate decisions.',
 'Specify a small study-task organizer. Define three acceptance criteria, its minimum data fields and three test cases including invalid input. Build a small prototype if tools are available, or submit a reproducible implementation plan with expected test outcomes clearly labeled as unexecuted. Include a repository or artifact reference when available, actual test results and remaining limitations. Never describe an unrun test as passed.',
 'An AI agent says the project is complete, but supplies no test results. What evidence would you require before accepting the work, and what additional review would you perform before deployment?'),
('module-ai-ethics',
 'Objective: make responsible choices about privacy, attribution and accountability. Obtain appropriate permission before using personal or confidential information with an AI tool. Minimize the information shared and use fictional data for practice. Follow the applicable course rules for AI assistance and disclose the assistance accurately. Check whether outputs disadvantage a group or reproduce unsupported stereotypes. Keep a human responsible for consequential decisions and provide a way to question or correct an outcome.',
 'A student proposes uploading classmates grades and names to an AI service to recommend study groups. Write a safer alternative using fictional or appropriately minimized data. Identify who must approve any real-data use, what information is unnecessary and how students could challenge an unsuitable recommendation. Submit the revised workflow and an AI-assistance disclosure for your work.',
 'An AI-generated report contains a persuasive stereotype about a student group. Explain why removing names alone does not address the issue and describe the review needed before sharing it.')
), replacements as (
 select m.id as module_id, v.slug, v.body
 from content c join public.learning_modules m on m.slug = c.module_slug
 cross join lateral (values ('lesson', c.lesson), ('lab', c.lab), ('check', c.reflection)) v(slug, body)
)
update public.learning_activities a set body = r.body
from replacements r
where a.module_id = r.module_id and a.slug = r.slug
  and a.body in (
    'Read the core idea for this competency and write down, in one sentence, where you expect it to break in practice. You will test that expectation in the lab.',
    'Run the technique on something real from your own work or study. Record what you did, what came back, and what you changed as a result. This output is kept and can be attached to a project submission later.',
    'Answer the check question in your own words: what would make you distrust a result in this area, and what would you do about it?'
  );
